import { ActivistItem } from "./types"

export const ACTIVISTS_DATA: ActivistItem[] = [
	{
		id: 1,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/data-logos/elliott-investment.png",
		activistName: "Elliott Investment Management L.P.",
		name: "Elliott Investment",
		type: "Hedge Fund",
		focus: "Corporate Governance",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 2,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 3,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 4,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 5,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 6,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 7,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 8,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 9,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 10,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 11,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 12,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 13,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 14,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 15,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 16,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 17,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 18,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 19,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 20,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 21,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 22,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	},
	{
		id: 23,
		countryImageSrc: "/assets/master-data/united-states.svg",
		activistImageSrc: "/public/data-logos/saba-capital.png",
		activistName: "Saba Capital Management, L.P.",
		name: "Saba Capital",
		type: "Private Equity",
		focus: "Operational Improvements",
		campaigns: 8,
		aum: 3000000000,
		trailing13dReturn1day: 2.5,
		trailing13dReturn1year: 15,
		trailing13dReturn3year: 40,
		trailing13dAbnormalReturn1year: 10,
		trailing13dAbnormalReturn3day: 8,
		portfolioFollowerAbnormalReturn1year: 40
	}
]
