import { CampaignsItem } from "./types"

export const CAMPAIGNS_DATA: CampaignsItem[] = [
	{
		id: 1,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 2,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 3,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 4,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 5,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 6,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 7,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 8,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 9,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 10,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 11,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 12,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 13,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 14,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 15,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 16,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 17,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 18,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 19,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 20,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 21,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 22,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	},
	{
		id: 23,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "15-05-2022",
		closing: "10-03-2023",
		activist: "Elliot Mgmt",
		activistImageSrc: "/data-logos/elliott-investment.png",
		target: "Salesforce",
		targetImageSrc: "/data-logos/salesforce.png",
		objective: "Improve governance",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "30-09-2022",
		settlementDate: "15-02-2024",
		outcome: "Board seats won"
	},
	{
		id: 24,
		countryImageSrc: "/assets/master-data/united-states.svg",
		fillingsDate: "2021-01-01",
		closing: "2021-01-01",
		activist: "Third Point",
		activistImageSrc: "/data-logos/third-point.png",
		target: "Sirius Point",
		targetImageSrc: "/data-logos/sirius-point.png",
		objective: "Objective",
		marketCap: 15,
		positionSize: 500,
		stake: 3.33,
		return: 25,
		abnormalReturn: 18,
		proxyContestDate: "2021-01-01",
		settlementDate: "2021-01-01",
		outcome: "Settlement reached"
	}
]
